const coding = ['js','ruby','java','py','swift','cpp']

// coding.forEach((item)=>{
//     console.log(item);
    
// })

// coding.forEach( (item,index, arr) => {
//     console.log(item, index, arr);
    
// } )

let studentInfo = [
    {name: 'Adhiraj Gupta', marks: '94%', class: 'B-Tech', address: 'Delhi'},
    {name: 'Nikhil Kumar', marks: '74%', class: 'BCA', address: 'Motihari'},
    {name: 'Rupesh Kumar Raushan', marks: '74%', class: 'BCA', address: 'Jandaha Jandaha'},
    {name: 'Arti Kumari', marks: '73%', class: 'BCA', address: 'Hajipur'},
    {name: 'Shivani Kumari', marks: '81%', class: 'BCA', address: 'Sitamarhi'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    {name: 'Arya Andita', marks: '78%', class: 'BCA', address: 'Motihari'},
    { name: 'Salmaan Ahmed', marks: '38%', class: '3rd', address: 'India' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Riya Sharma', marks: '85%', class: '10th', address: '123, ABC Colony, Delhi' },
    { name: 'Rohan Patel', marks: '70%', class: '12th', address: '456, XYZ Street, Mumbai' },
    { name: 'Priya Singh', marks: '95%', class: '8th', address: '789, PQR Nagar, Bangalore' },
    { name: 'Ankit Gupta', marks: '60%', class: '9th', address: '101, LMN Road, Kolkata' },
    { name: 'Ankit Gupta', marks: '60%', class: '9th', address: '101, LMN Road, Kolkata' },
    { name: 'Neha Verma', marks: '80%', class: '11th', address: '222, DEF Avenue, Chennai' },
    { name: 'Neha Verma', marks: '80%', class: '11th', address: '222, DEF Avenue, Chennai' },
    { name: 'Manoj Kumar', marks: '75%', class: '10th', address: '333, GHI Lane, Hyderabad' },
    { name: 'Pooja Mishra', marks: '88%', class: '12th', address: '444, STU Colony, Pune' },
    { name: 'Rajesh Singhania', marks: '92%', class: '9th', address: '555, VWX Street, Jaipur' }
]

studentInfo.forEach( (student, index) => {
    console.log(`SrNo: ${index+1} | Name of Student: ${student.name}, Marks: ${student.marks}, Class: ${student.class}, Address: ${student.address}`);
}) 